#!/bin/bash

#   /    Context:                     https://ctx.ist
# ,'`./    do you remember?
# `.,'\
#   \    Copyright 2025-present Context contributors.
#                 SPDX-License-Identifier: Apache-2.0

# Auto-save session transcript on exit (including Ctrl+C)
# This hook is triggered by Claude Code's SessionEnd event
#
# Generated by: ctx init
# Requires: ctx in PATH (for other hooks, not this script)

# Read hook input from stdin (JSON)
HOOK_INPUT=$(cat)

# Extract transcript_path and session info
TRANSCRIPT_PATH=$(echo "$HOOK_INPUT" | jq -r '.transcript_path // empty')
SESSION_ID=$(echo "$HOOK_INPUT" | jq -r '.session_id // "unknown"')
REASON=$(echo "$HOOK_INPUT" | jq -r '.reason // "unknown"')
PROJECT_DIR=$(echo "$HOOK_INPUT" | jq -r '.cwd // "."')

# Only proceed if we have a transcript path
if [ -z "$TRANSCRIPT_PATH" ] || [ ! -f "$TRANSCRIPT_PATH" ]; then
    exit 0
fi

# Create sessions directory if it doesn't exist
SESSIONS_DIR="$PROJECT_DIR/.context/sessions"
mkdir -p "$SESSIONS_DIR"

# Generate filename with timestamp: YYYY-MM-DD-HHMMSS-session-<reason>.jsonl
TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
FILENAME="$SESSIONS_DIR/${TIMESTAMP}-session-${REASON}.jsonl"

# Copy the transcript
cp "$TRANSCRIPT_PATH" "$FILENAME"

# Extract session start time from transcript (first entry timestamp) if possible
START_TIME=""
if [ -f "$TRANSCRIPT_PATH" ]; then
    # Try to get timestamp from first line of transcript
    FIRST_TS=$(head -1 "$TRANSCRIPT_PATH" | jq -r '.timestamp // empty' 2>/dev/null)
    if [ -n "$FIRST_TS" ]; then
        # Convert to YYYY-MM-DD-HHMM format
        START_TIME=$(date -d "$FIRST_TS" +%Y-%m-%d-%H%M 2>/dev/null || echo "")
    fi
fi

# Fall back to current time if we couldn't extract start time
if [ -z "$START_TIME" ]; then
    START_TIME=$(date +%Y-%m-%d-%H%M)
fi

END_TIME=$(date +%Y-%m-%d-%H%M)

# Also create a human-readable summary
SUMMARY_FILE="$SESSIONS_DIR/${TIMESTAMP}-session-${REASON}-summary.md"
cat > "$SUMMARY_FILE" << EOF
# Session Auto-Save

**Saved**: $(date -Iseconds)
**Reason**: $REASON
**Session ID**: $SESSION_ID
**Transcript**: ${TIMESTAMP}-session-${REASON}.jsonl
**start_time**: $START_TIME
**end_time**: $END_TIME

This session was auto-saved by the SessionEnd hook.
To analyze the full transcript, read the .jsonl file.
EOF

exit 0
