//   /    Context:                     https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package config

// Obsidian vault output directory constants.
const (
	// ObsidianDirName is the default output directory for the Obsidian vault
	// within .context/.
	ObsidianDirName = "journal-obsidian"
	// ObsidianDirEntries is the subdirectory for journal entry files.
	ObsidianDirEntries = "entries"
	// ObsidianConfigDir is the Obsidian configuration directory name.
	ObsidianConfigDir = ".obsidian"
)

// Obsidian vault configuration.
const (
	// ObsidianAppConfig is the minimal app.json content that enforces
	// wikilink mode and shows frontmatter properties.
	ObsidianAppConfig = `{
  "useMarkdownLinks": false,
  "showFrontmatter": true,
  "strictLineBreaks": false
}
`
	// ObsidianAppConfigFile is the Obsidian app configuration filename.
	ObsidianAppConfigFile = "app.json"
)

// Obsidian MOC (Map of Content) page filenames.
const (
	// ObsidianMOCPrefix is prepended to MOC filenames so they sort first
	// in the Obsidian file explorer.
	ObsidianMOCPrefix = "_"
	// ObsidianHomeMOC is the root navigation hub filename.
	ObsidianHomeMOC = "Home.md"
	// ObsidianTopicsMOC is the topics index MOC filename.
	ObsidianTopicsMOC = "_Topics.md"
	// ObsidianFilesMOC is the key files index MOC filename.
	ObsidianFilesMOC = "_Key Files.md"
	// ObsidianTypesMOC is the session types index MOC filename.
	ObsidianTypesMOC = "_Session Types.md"
)

// Obsidian vault format templates.
const (
	// ObsidianWikilinkFmt formats a wikilink with display text.
	// Args: target, display.
	ObsidianWikilinkFmt = "[[%s|%s]]"
	// ObsidianWikilinkPlain formats a plain wikilink (no display text).
	// Args: target.
	ObsidianWikilinkPlain = "[[%s]]"
	// ObsidianRelatedHeading is the section heading for the related footer.
	ObsidianRelatedHeading = "## Related Sessions"
	// ObsidianSeeAlso is the label for the see-also section in the footer.
	ObsidianSeeAlso = "**See also**:"
)

// Obsidian vault README template.
const ObsidianReadme = `# journal-obsidian (generated)

This directory is generated by ` + "`ctx journal obsidian`" + ` and is read-only.
Do not edit files here — changes will be overwritten on the next run.

## To update

1. Edit source entries in ` + "`%s/`" + `
2. Regenerate:

` + "```" + `
ctx journal obsidian
` + "```" + `

## Usage

Open this directory as an Obsidian vault:

1. Open Obsidian
2. Choose "Open folder as vault"
3. Select this directory
`
