//   /    Context:                     https://ctx.ist
// ,'`./    do you remember?
// `.,'\
//   \    Copyright 2026-present Context contributors.
//                 SPDX-License-Identifier: Apache-2.0

package config

// Journal site format templates.
//
// These templates define the structure of generated journal site pages.
// Each uses fmt.Sprintf verbs for interpolation.
const (
	// TplJournalSiteReadme formats the README for the journal-site directory.
	// Args: journalDir.
	TplJournalSiteReadme = `# journal-site (generated)

This directory is generated by ` + "`ctx journal site`" + ` and is read-only.
Do not edit files here — changes will be overwritten on the next run.

## To update

1. Edit source entries in ` + "`%s/`" + `
2. Regenerate:

` + "```" + `
ctx journal site          # generate
ctx journal site --serve  # generate and preview
` + "```" + `
`

	// TplJournalIndexIntro is the introductory line on the journal index.
	TplJournalIndexIntro = "Browse your AI session history."

	// TplJournalIndexStats formats the session/suggestion count line.
	// Args: regular count, suggestion count.
	TplJournalIndexStats = "**Sessions**: %d | **Suggestions**: %d"

	// TplJournalSuggestionsNote is the description under the suggestions heading.
	TplJournalSuggestionsNote = "*Auto-generated suggestion prompts from Claude Code.*"

	// TplJournalMonthHeading formats a month section heading.
	// Args: month string (YYYY-MM).
	TplJournalMonthHeading = "## %s"

	// TplJournalIndexEntry formats a single entry in the journal index.
	// Args: timeStr, title, link, project, size.
	TplJournalIndexEntry = "- %s[%s](%s.md)%s `%s`"

	// TplJournalIndexSummary formats the summary line below an index entry.
	// Args: summary text. Indented to nest visually under the parent bullet.
	TplJournalIndexSummary = "    *%s*"

	// TplJournalSummaryAdmonition formats the summary as an abstract admonition
	// on individual journal entry pages.
	// Args: summary text.
	TplJournalSummaryAdmonition = "!!! abstract \"Summary\"\n    %s"

	// TplJournalSourceLink formats the "View source" link injected into entries.
	// Args: absPath, relPath, relPath.
	TplJournalSourceLink = `*[View source](file://%s) · <code>%s</code>*` +
		` <button onclick="navigator.clipboard.writeText('%s')" title="Copy path"` +
		` style="cursor:pointer;border:none;background:none;font-size:0.8em;vertical-align:middle">` +
		`&#x2398;</button>`

	// TplJournalTopicStats formats the topics index summary line.
	// Args: topic count, session count, popular count, longtail count.
	TplJournalTopicStats = "**%d topics** across **%d sessions**— **%d popular**, **%d long-tail**"

	// TplJournalTopicPageStats formats an individual topic page summary.
	// Args: session count.
	TplJournalTopicPageStats = "**%d sessions** with this topic."

	// TplJournalFileStats formats the key files index summary line.
	// Args: file count, session count, popular count, longtail count.
	TplJournalFileStats = "**%d files** across **%d sessions** — **%d popular**, **%d long-tail**"

	// TplJournalFilePageStats formats an individual key file page summary.
	// Args: session count.
	TplJournalFilePageStats = "**%d sessions** touching this file."

	// TplJournalTypeStats formats the session types index summary line.
	// Args: type count, session count.
	TplJournalTypeStats = "**%d types** across **%d sessions**"

	// TplJournalTypePageStats formats an individual type page summary.
	// Args: session count, type name.
	TplJournalTypePageStats = "**%d sessions** of type *%s*."

	// TplJournalPageHeading formats a Markdown heading for an index page.
	// Args: name.
	TplJournalPageHeading = "# %s"

	// TplJournalCodePageHeading formats a Markdown heading with code styling.
	// Args: path.
	TplJournalCodePageHeading = "# `%s`"

	// TplJournalSubpageEntry formats a session link on a subpage (topic, file, type).
	// Args: timeStr, title, linkPrefix, link.
	TplJournalSubpageEntry = "- %s[%s](%s%s.md)"

	// TplJournalLongtailEntry formats an inline longtail topic entry.
	// Args: name, title, link.
	TplJournalLongtailEntry = "- **%s** — [%s](../%s.md)"

	// TplJournalLongtailCodeEntry formats an inline longtail key file entry.
	// Args: path, title, link.
	TplJournalLongtailCodeEntry = "- `%s` — [%s](../%s.md)"

	// TplJournalNavItem formats a navigation item in zensical.toml.
	// Args: label, path.
	TplJournalNavItem = `  { "%s" = "%s" },`

	// TplJournalNavSection formats a navigation section opening.
	// Args: label.
	TplJournalNavSection = `  { "%s" = [`

	// TplJournalNavSessionItem formats a session entry in navigation.
	// Args: title, filename.
	TplJournalNavSessionItem = `    { "%s" = "%s" },`

	// TplZensicalProject is the [project] section of zensical.toml.
	TplZensicalProject = `[project]
site_name = "ctx: Session Journal"
site_description = "AI session history and notes"
site_author = "Jose Alekhinne <alekhinejose@gmail.com>"
site_url = "https://ctx.ist/"
repo_url = "https://github.com/ActiveMemory/ctx"
repo_name = "ActiveMemory/ctx"
copyright = """
Copyright &copy; 2026&ndash;present <a href="https://github.com/ActiveMemory/ctx/">Context contributors</a>.<br>
<a href="https://github.com/ActiveMemory/ctx"><code>ctx</code>'s code</a> is distributed under
<a href="https://github.com/ActiveMemory/ctx/blob/main/LICENSE"><strong>Apache (v2.0)</strong></a>.<br>
"""

`

	// TplZensicalTheme is the theme and extras section of zensical.toml.
	TplZensicalTheme = `

[project.theme]
language = "en"
features = [
    "content.code.copy",
    "navigation.instant",
    "navigation.top",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/ActiveMemory/ctx"

[[project.extra.social]]
icon = "fontawesome/brands/stack-exchange"
link = "https://web.libera.chat/#ctx"

[project.extra]
generator = false

# Markdown extensions — mirrors zensical defaults but disables Pygments
# code highlighting. Journal entries use <pre><code> for user turns and
# fenced blocks for tool output; pymdownx.highlight with Pygments on
# hijacks <pre><code> patterns, transforming block boundaries and
# swallowing subsequent content.
[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
toc = { permalink = true }

[project.markdown_extensions.pymdownx]
betterem = {}
caret = {}
details = {}
inlinehilite = {}
keys = {}
magiclink = {}
mark = {}
smartsymbols = {}
tasklist = { custom_checkbox = true }
tilde = {}

[project.markdown_extensions.pymdownx.highlight]
use_pygments = false

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [{ name = "mermaid", class = "mermaid" }]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
`

	// TplZensicalExtraCSS is the extra_css line for zensical.toml.
	// Must appear under [project] (after nav, before [project.theme]).
	TplZensicalExtraCSS = `extra_css = ["stylesheets/extra.css"]`

	// JournalExtraCSS is deprecated — the stylesheet is now embedded
	// from internal/cli/journal/extra.css via go:embed.
	// This constant is kept only as a fallback reference.
	JournalExtraCSS = ""
)
